export const metadata = {
    title: "Reserve at Mile (Toronto) | KU Sports",
    description: "Generated by create next app",
  };
  
  export default function SearchLayout({
    children,
  }: {
    children: React.ReactNode;
  }) {
    /*The `<>` and `</>` are shorthand for a React fragment, 
      which allows multiple children to be returned without adding an extra DOM element. */
    return <> {children}</>;
  }
  