// nested layout for sport pages
import SportHeader from "./components/SportHeader";

export const metadata = {
  title: "sport | KU sport",
  description: "Generated by create next app",
};

export default function SportLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { slug: string };
}) {
  // query for sport data

  return (
    <>
      <SportHeader name={params.slug} />
      {/* DESCRIPTION PORTION */}
      <div className="flex flex-col items-start justify-between w-11/12 m-auto md:w-2/3 -mt-11 md:flex-row">
        {children}
      </div>
      {/* DESCRIPTION PORTION */}
    </>
  );
}
